apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamrss-publisher
spec:
  template:
    spec:
      volumes:
        - name: htpasswd
          secret:
            secretName: hamrss-publisher-htpasswd
      containers:
        - name: authproxy
          volumeMounts:
            - name: htpasswd
              mountPath: /auth
          image: docker.io/nginxinc/nginx-unprivileged:mainline
          ports:
            - name: hamrss
              containerPort: 9090
          command:
            - /bin/bash
            - -c
            - |
              cat > /etc/nginx/conf.d/default.conf <<EOF
              server {
                  listen 9090;
                  server_name hamrss.oddbit.com;

                  location / {
                      auth_basic "HamRSS";
                      auth_basic_user_file /auth/htpasswd;
                      proxy_pass http://localhost:8080;
                  }
              }
              EOF
              exec nginx -g 'daemon off;'
