# https://kubernetes.io/docs/concepts/workloads/controllers/job/
apiVersion: batch/v1
kind: Job
metadata:
  name: generate-miniflux-password
  labels:
    component: generate-miniflux-password
spec:
  template:
    metadata:
      name: myjob
      labels:
        component: generate-miniflux-password
    spec:
      restartPolicy: Never
      serviceAccountName: password-generator
      containers:
        - name: generate-miniflux-password
          image: cli
          envFrom:
            - configMapRef:
                name: hamrss-config
          command:
            - /bin/bash
            - -c
            - |
              cd /tmp
              MINIFLUX_DB_PASSWORD=$(tr -dc 'A-Za-z0-9!?%=' < /dev/urandom | head -c 20)
              oc get secret miniflux-secrets -o name ||
              oc create secret generic miniflux-secrets \
                --from-literal=MINIFLUX_DB_PASSWORD="$MINIFLUX_DB_PASSWORD" \
                --from-literal=MINIFLUX_DB_USER="$MINIFLUX_DB_USER" \
                --from-literal=MINIFLUX_DB_NAME="$MINIFLUX_DB_NAME" \
                --from-literal=MINIFLUX_DB_URL="host=postgres user=${MINIFLUX_DB_USER} password=${MINIFLUX_DB_PASSWORD} dbname=${MINIFLUX_DB_NAME} sslmode=disable"
