apiVersion: v1
kind: ServiceAccount
metadata:
  name: password-generator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: password-generator
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: password-generator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: password-generator
subjects:
  - kind: ServiceAccount
    name: password-generator
    namespace: default
